import os    

print("Program started")

replacements = {'(*1)':'Option1 :',
                '(*2)':'Option2 :',
                '(*3)':'Option3 :',
                '(*4)':'Option4 :',
                'A) ':'Option1 :',
                'B) ':'Option2 :',
                'C) ':'Option3 :',
                'D) ':'Option4 :',
 #               '150. ':'Question : ',
 #               '149. ':'Question : ',
 #               '148. ':'Question : ',
 #               '147. ':'Question : ',
 #               '146. ':'Question : ',
 #               '145. ':'Question : ',
 #               '144. ':'Question : ',
 #               '143. ':'Question : ',
 #               '142. ':'Question : ',
 #               '141. ':'Question : ',
 #               '140. ':'Question : ',
 #               '139. ':'Question : ',
 #               '138. ':'Question : ',
 #               '137. ':'Question : ',
 #               '136. ':'Question : ',
 #               '135. ':'Question : ',
 #               '134. ':'Question : ',
 #               '133. ':'Question : ',
 #               '132. ':'Question : ',
 #               '131. ':'Question : ',
 #               '130. ':'Question : ',
 #               '129. ':'Question : ',
 #               '128. ':'Question : ',
 #               '127. ':'Question : ',
 #               '126. ':'Question : ',
 #               '125. ':'Question : ',
 #               '124. ':'Question : ',
 #               '123. ':'Question : ',
 #               '122. ':'Question : ',
 #               '121. ':'Question : ',
 #               '120. ': 'Question : ',
 #               '119. ': 'Question : ',
 #               '118. ': 'Question : ',
 #               '117. ': 'Question : ',
 #               '116. ': 'Question : ',
 #               '115. ': 'Question : ',
 #               '114 ': 'Question : ',
 #               '113. ': 'Question : ',
 #               '112. ': 'Question : ',
 #               '111. ': 'Question : ',
 #               '110. ': 'Question : ',
 #               '109. ': 'Question : ',
 #               '108. ': 'Question : ',
 #               '107. ': 'Question : ',
 #               '106. ': 'Question : ',
 #               '105. ': 'Question : ',
 #               '104. ': 'Question : ',
 #               '103. ': 'Question : ',
 #               '102. ': 'Question : ',
 #               '101. ': 'Question : ',
 #               '100. ': 'Question : ',
 #               '99. ': 'Question : ',
 #               '98. ': 'Question : ',
 #               '97. ': 'Question : ',
 #               '96. ': 'Question : ',
  #              '95. ': 'Question : ',
  #              '94. ': 'Question : ',
  #              '93. ': 'Question : ',
   #             '92. ': 'Question : ',
    #            '91. ': 'Question : ',
                '90) ': 'Question : ',
                '89) ': 'Question : ',
                '88) ': 'Question : ',
                '87) ': 'Question : ',
                '86) ': 'Question : ',
                '85) ': 'Question : ',
                '84) ': 'Question : ',
                '83) ': 'Question : ',
                '82) ': 'Question : ',
                '81) ': 'Question : ',
                '80) ': 'Question : ',
                '79) ': 'Question : ',
                '78) ': 'Question : ',
                '77) ': 'Question : ',
                '76) ': 'Question : ',
                '75) ': 'Question : ',
                '74) ': 'Question : ',
                '73) ': 'Question : ',
                '72) ': 'Question : ',
                '71) ': 'Question : ',
                '70) ': 'Question : ',
                '69) ': 'Question : ',
                '68) ': 'Question : ',
                '67) ': 'Question : ',
                '66) ': 'Question : ',
                '65) ': 'Question : ',
                '64) ': 'Question : ',
                '63) ': 'Question : ',
                '62) ': 'Question : ',
                '61) ': 'Question : ',
                '60) ': 'Question : ',
                '59) ': 'Question : ',
                '58) ': 'Question : ',
                '57) ': 'Question : ',
                '56) ': 'Question : ',
                '55) ': 'Question : ',
                '54) ': 'Question : ',
                '53) ': 'Question : ',
                '52) ': 'Question : ',
                '51) ': 'Question : ',
                '50) ': 'Question : ',
                '49) ': 'Question : ',
                '48) ': 'Question : ',
                '47) ': 'Question : ',
                '46) ': 'Question : ',
                '45) ': 'Question : ',
                '44) ': 'Question : ',
                '43) ': 'Question : ',
                '42) ': 'Question : ',
                '41) ': 'Question : ',
                '40) ': 'Question : ',
                '39) ': 'Question : ',
                '38) ': 'Question : ',
                '37) ': 'Question : ',
                '36) ': 'Question : ',
                '35) ': 'Question : ',
                '34) ': 'Question : ',
                '33) ': 'Question : ',
                '32) ': 'Question : ',
                '31) ': 'Question : ',
                '30) ': 'Question : ',
                '29) ': 'Question : ',
                '28) ': 'Question : ',
                '27) ': 'Question : ',
                '26) ': 'Question : ',
                '25) ': 'Question : ',
                '24) ': 'Question : ',
                '23) ': 'Question : ',
                '22) ': 'Question : ',
                '21) ': 'Question : ',
                '20) ': 'Question : ',
                '19) ': 'Question : ',
                '18) ': 'Question : ',
                '17) ': 'Question : ',
                '16) ': 'Question : ',
                '15) ': 'Question : ',
                '14) ': 'Question : ',
                '13) ': 'Question : ',
                '12) ': 'Question : ',
                '11) ': 'Question : ',
                '10) ': 'Question : ',
                '9) ': 'Question : ',
                '8) ': 'Question : ',
                '7) ': 'Question : ',
                '6) ': 'Question : ',
                '5) ': 'Question : ',
                '4) ': 'Question : ',
                '3) ': 'Question : ',
                '2) ': 'Question : ',
                '1) ': 'Question : ',
 #               '90. ': 'Question : ',
 #               '89. ': 'Question : ',
 #               '88. ': 'Question : ',
 #               '87. ': 'Question : ',
 #               '86. ': 'Question : ',
 #               '85. ': 'Question : ',
 #               '84. ': 'Question : ',
 #               '83. ': 'Question : ',
 #               '82. ': 'Question : ',
 #               '81. ': 'Question : ',
 #               '80. ': 'Question : ',
 #               '79. ': 'Question : ',
 #               '78. ': 'Question : ',
 #               '77. ': 'Question : ',
 #               '76. ': 'Question : ',
 #               '75. ': 'Question : ',
 #               '74. ': 'Question : ',
 #               '73. ': 'Question : ',
 #               '72. ': 'Question : ',
 #               '71. ': 'Question : ',
 #               '70. ': 'Question : ',
 #               '69. ': 'Question : ',
 #               '68. ': 'Question : ',
 #               '67. ': 'Question : ',
 #               '66. ': 'Question : ',
 #               '65. ': 'Question : ',
 #               '64. ': 'Question : ',
 #               '63. ': 'Question : ',
 #               '62. ': 'Question : ',
 #               '61. ': 'Question : ',
 #               '60. ': 'Question : ',
 #               '59. ': 'Question : ',
 #               '58. ': 'Question : ',
 #               '57. ': 'Question : ',
 #               '56. ': 'Question : ',
 #               '55. ': 'Question : ',
 #               '54. ': 'Question : ',
 #               '53. ': 'Question : ',
 #               '52. ': 'Question : ',
 #               '51. ': 'Question : ',
 #               '50. ': 'Question : ',
 #               '49. ': 'Question : ',
 #               '48. ': 'Question : ',
 #               '47. ': 'Question : ',
 #               '46. ': 'Question : ',
 #               '45. ': 'Question : ',
 #               '44. ': 'Question : ',
 #               '43. ': 'Question : ',
 #               '42. ': 'Question : ',
 #               '41. ': 'Question : ',
 #               '40. ': 'Question : ',
 #               '39. ': 'Question : ',
 #               '38. ': 'Question : ',
 #               '37. ': 'Question : ',
 #               '36. ': 'Question : ',
 #               '35. ': 'Question : ',
 #               '34. ': 'Question : ',
 #               '33. ': 'Question : ',
 #               '32. ': 'Question : ',
 #               '31. ': 'Question : ',
 #               '30. ': 'Question : ',
 #               '29. ': 'Question : ',
 #               '28. ': 'Question : ',
 #               '27. ': 'Question : ',
 #               '26. ': 'Question : ',
 #               '25. ': 'Question : ',
 #               '24. ': 'Question : ',
 #               '23. ': 'Question : ',
 #               '22. ': 'Question : ',
 #               '21. ': 'Question : ',
 #               '20. ': 'Question : ',
 #               '19. ': 'Question : ',
 #               '18. ': 'Question : ',
 #               '17. ': 'Question : ',
 #               '16. ': 'Question : ',
 #               '15. ': 'Question : ',
 #               '14. ': 'Question : ',
 #               '13. ': 'Question : ',
 #               '12. ': 'Question : ',
 #               '11. ': 'Question : ',
 #               '10. ': 'Question : ',
                'Answer - ':'Answer : ' }

with open('TET.txt') as infile, open('TET1.txt', 'w') as outfile:
    for line in infile:
        for src, target in replacements.items():
            line = line.replace(src, target)
        outfile.write(line)

print("Program ends")
